version: '2'
services:
  stationeers:
    container_name: stationeers
    image: stationeers:0.1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "27500:27500/tcp"
      - "27500:27500/udp"
      - "27015:27015/udp"
    volumes:
      - /srv/s:/stationeers
    environment: 
      - SAVE_INTERVAL="300" 
      - CLEAR_INTERVAL="60"  
      - WORLD_TYPE="Moon" 
      - WORLD_NAME="Base"
      - SERVERNAME="Stationeers" 
      - GAMEPORT="27500" 
      - UPDATERPORT="27015" 
      - PASSWORD="" 
      - ADMINPASSWORD="AdminPass" 
      - MAPNAME="Moon" 
      - DESCRIPTION="Stationeers" 
      - MAXPLAYER="10" 
      - RCONPASSWORD="Stationeers"
